import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const compat = new FlatCompat({ baseDirectory: __dirname });

export default [
  // next-env.d.ts is generated by Next (triple-slash refs are expected);
  // config files legitimately use anonymous default exports.
  { ignores: [".next/**", "node_modules/**", "next-env.d.ts", "*.config.mjs", "*.config.ts"] },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];
